### ISSUE TITLE
Configurar base de datos

### ISSUE THREAD

**Issue by fjcroquevielle** [IIC2513-2021-1/syllabus-1#1]
En la wiki aparecen una serie de instrucciones para comenzar con el proyecto. Bajé los programas necesarios, el template y descarge psql, sin embargo, después se me dice: 'crear la base de datos que usarás para tu aplicación (createdb <database-name>) y configurarla en src/config/database.js'. Cree la base de datos, sin embargo no se a que se refiere con configurarla. Podrían ayudarme con esto? Gracias!

**Comment by sivicencio** [comment]
Hola @fjcroquevielle, creo que publicaste [el mismo issue](https://github.com/IIC2513-2021-1/projects/issues/2) en el repositorio de los proyectos. De todas formas, haré un resumen de la respuesta que dio el ayudante en aquella issue, por si alguien ve esto acá.

(Como recomendación, dudas ligadas al proyecto deben ir en ese otro repositorio)

**Aún no es necesario que utilicen el template**, pues la E1.0 sólo se compone de un conjunto de archivos HTML y CSS. Tenemos que introducir el uso del template en el curso aún, lo que ocurrirá en un par de semanas más. Además, irá acompañado de cápsulas que les ayudarán a instalar todo lo necesario. Paciencia por ahora.
